services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: taskflowdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-service:
    build: ./api-service
    ports:
      - "3000:3000"
    env_file:
      - ./api-service/.env
    environment:
      - DB_HOST=postgres
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: taskflow
        awslogs-stream: api-service

  worker-service:
    build: ./worker-service
    env_file:
      - ./worker-service/.env
    environment:
      - DB_HOST=postgres
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: taskflow
        awslogs-stream: worker-service

volumes:
  pgdata: